### ISSUE TITLE
No license listed for QuickPermissions-Kotlin

### ISSUE THREAD

**Issue by javadude** [QuickPermissions/QuickPermissions-Kotlin#12]
Please add a license file to QuickPermissions-Kotlin? I assume it's Apache 2 like QuickPermissions.

**Comment by javadude** [comment]
Hi! Can you please accept the pull request to resolve this issue? I'd love to use this library but cannot unless it has an explicit license. Thanks!

**Comment by kirtan403** [comment]
https://github.com/QuickPermissions/QuickPermissions-Kotlin/pull/13 
Merge request accepted

**Comment by javadude** [comment]
Thanks much!
