### ISSUE TITLE
permissionsDeniedMethod is never called

### ISSUE THREAD

**Issue by juancruzgs** [QuickPermissions/QuickPermissions-Kotlin#6]
When `handleRationale = false` and `handlePermanentlyDenied = false` the method to handle denied permissions is never called.
When I deny the permission in the Android dialog, my callback is never called.

This is my code:

```
val options = QuickPermissionsOptions(
    handleRationale = false,
    handlePermanentlyDenied = false,
    permissionsDeniedMethod = { 
        // This method is never called
    }
)

activity.runWithPermissions(Manifest.permission.ACCESS_FINE_LOCATION, options = options) {
    // Works Ok
}
```

**Comment by kirtan403** [comment]
This issue is now fixed

**Comment by kirtan403** [comment]
New version released with fix: https://github.com/QuickPermissions/QuickPermissions-Kotlin/releases/tag/0.4.0
