### ISSUE TITLE
Positive Button & Negative Button all white color

### ISSUE THREAD

**Issue by asdfghj1237890** [QuickPermissions/QuickPermissions-Kotlin#8]
Hi, i am using this library recently and i found that when i just using this from the readme

> fun methodWithPermissions() = runWithPermissions(Manifest.permission.CAMERA,Manifest.permission.RECORD_AUDIO) {
      Toast.makeText(this, "Camera and audio recording permissions granted", 
      Toast.LENGTH_SHORT).show();
}

 buttons all are white color text.

Screenshot as below:
https://imgur.com/a/f9Q7I6w

**Comment by kirtan403** [comment]
Can you please provide the following details?

Device Manufacturer: 
ROM Name (Stock, MIUI etc) :
ROM Version (if any): 
Android Version:

**Comment by asdfghj1237890** [comment]
> Can you please provide the following details?
> 
> Device Manufacturer:
> ROM Name (Stock, MIUI etc) :
> ROM Version (if any):
> Android Version:

with the android studio emulator below
Pixel 2 XL 
Android 8.0 API 26

**Comment by m4limo** [comment]
@asdfghj1237890 maybe it is just a styling issue? 

try to style the alertDialog accordingly: 

`<style name="AlertDialogTheme" parent="Theme.AppCompat.Light.Dialog.Alert">
    <item name="buttonBarNegativeButtonStyle">@style/NegativeButtonStyle</item>
    <item name="buttonBarPositiveButtonStyle">@style/PositiveButtonStyle</item>
</style>

<style name="NegativeButtonStyle" parent="Widget.AppCompat.Button.ButtonBar.AlertDialog">
    <item name="android:textColor">#f00</item>
</style>

<style name="PositiveButtonStyle" parent="Widget.AppCompat.Button.ButtonBar.AlertDialog">
    <item name="android:textColor">#00f</item>
</style>`

and use `<item name="alertDialogTheme">@style/AlertDialogTheme</item>` in your AppTheme

**Comment by kirtan403** [comment]
@asdfghj1237890 Hi, is your issue fixed, now?

**Comment by kirtan403** [comment]
Maybe your accent color is white? The same issue has happened with me also. Try to apply an alert dialog theme with overridden colorAccent can also solve this issue.
